default:
  title: "Pushkind Dashboards"
  oauth2_scopes: "openid email profile"
  static_upload_path: upload
  sqlalchemy_database_uri: sqlite:///app.db
  file_upload_suffix: ".df"
  admins: []

development:
  debug: true

testing:
  title: testing
  login_disabled: true
  sqlalchemy_database_uri: sqlite://
  secret_key: testing
