"""empty message

Revision ID: 0a127af41cea
Revises: 8040bcb4cf61
Create Date: 2023-12-09 00:39:27.051099

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a127af41cea"
down_revision = "8040bcb4cf61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_column("file_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_url", sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
