"""empty message

Revision ID: 2e3aaa69f8d2
Revises: a79ea56282ac
Create Date: 2023-12-12 01:12:27.160877

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e3aaa69f8d2"
down_revision = "a79ea56282ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("report_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("report_id", "reports", ["report_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("report_id")

    # ### end Alembic commands ###
