"""empty message

Revision ID: 5dffad5efc0b
Revises: 0a127af41cea
Create Date: 2023-12-12 00:54:23.605423

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5dffad5efc0b"
down_revision = "0a127af41cea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
