"""empty message

Revision ID: a79ea56282ac
Revises: 5dffad5efc0b
Create Date: 2023-12-12 00:54:58.560798

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a79ea56282ac"
down_revision = "5dffad5efc0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    # ### end Alembic commands ###
