"""empty message

Revision ID: dae9ddb3f872
Revises: 2e3aaa69f8d2
Create Date: 2023-12-12 15:39:17.516900

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dae9ddb3f872"
down_revision = "2e3aaa69f8d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_files")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "import_fn",
                sa.String(length=128),
                server_default="pushboards.main.upload.excel_processor.process",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_column("import_fn")

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    op.create_table(
        "_alembic_tmp_files",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("file_path", sa.VARCHAR(length=128), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("report_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], name="report_id"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
