name: Deploy main

on:
  workflow_run:
    workflows: ["Lint and Pytest"]
    branches: [ main ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.CICD_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Pull
        run: ssh cicd@reports.pushkind.com "cd /var/www6/html/ && git pull origin main && supervisorctl restart reports_dev"
  on-failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - run: |
            echo 'The triggering workflow failed'
            exit 1
